#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
setxkbmap -variant colemak
sxhkd&
setxkbmap -variant colemak
bspc rule -r "*"
xsetroot -cursor_name left_ptr
# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
# mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

# if ! echo "$mainmonitor" | grep LVDS-1 >/dev/null 2>&1; then
# 	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
# fi

# my_laptop_external_monitor=$(xrandr --query | grep 'VGA-1')
# if [[ $my_laptop_external_monitor == *connected* ]]; then
	bspc monitor VGA-1 -d 1 2 3 4 5
	bspc monitor LVDS-1 -d  6 7 8 9 0
	~/.screenlayout/layout.sh
	launch_polybar&
# else
# bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 0
# ~/.screenlayout/layout1m.sh
# launch_polybar1m&
# fi

bspc config border_width 3
bspc config window_gap 7
bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

# dropdownname="dropdown"
# bspc query -N -n .hidden >/dev/null || setsid $TERMINAL -n "$dropdownname" -e dropdown >/dev/null 2>&1 &
# bspc rule -a St:$dropdownname hidden=on
# bspc rule -a St:$dropdownname sticky=on
# bspc rule -a St:$dropdownname state=floating
bspc rule -a Screenkey manage=off
# bspc rule -a st state=fullscreen
bspc config external_rules_command "$(which floaters)"
bspc rule -a Zathura state=tiled

setbg&
