#!/bin/sh

setxkbmap -variant colemak
sxhkd&
setxkbmap -variant colemak
bspc rule -r "*"
xsetroot -cursor_name left_ptr

case $(hostname) in
	dell)
		bspc monitor DP-3 -d 1 2 3
		;;
	nixpad)
		bspc monitor LVDS-1 -d 1 2 3
		;;
	*)
		;;
esac

launch_polybar&

bspc config border_width 3
bspc config window_gap 7
bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

setbg&
