#!/bin/sh


setxkbmap -variant colemak
sxhkd&
setxkbmap -variant colemak
bspc rule -r "*"
xsetroot -cursor_name left_ptr


case $(hostname) in
	dell)
    if [ $(xrandr --query | grep " connected" | cut -d" " -f1 | grep HDMI) ]; then
      xrandr --output HDMI-1 --right-of DP-3
      bspc monitor DP-3 -d 1 2 3 4
      bspc monitor HDMI-1 -d 5 6 7 8
    else
      bspc monitor DP-3 -d 1 2 3 4
    fi

		;;
	nixpad)
		bspc monitor LVDS-1 -d 1 2 3 4
		;;
	*)
		;;
esac


launch_polybar&


bspc config border_width 1
bspc config window_gap 1
bspc config top_padding 25	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

setbg&
