#!/usr/bin/env python3

import imaplib

mail = imaplib.IMAP4_SSL('imap.gmail.com')
mail.login(input(), input())
mail.list()

mail.select('inbox')

_, data = mail.search(None, '(UNSEEN)')

# Print the count of all unread messages
inboxfiles = len(data[0].split())
print(inboxfiles)

mail.close()

mail.logout()
