# ui stuff
colorscheme gruvbox
add-highlighter global/ number-lines

# fzf stuff
source "~/.config/kak/plugins/fzf.kak/rc/fzf.kak"
source "~/.config/kak/plugins/fzf.kak/rc/modules/fzf-file.kak"   # fzf file chooser
source "~/.config/kak/plugins/fzf.kak/rc/modules/fzf-buffer.kak" # switching buffers with fzf
source "~/.config/kak/plugins/fzf.kak/rc/modules/fzf-search.kak" # search within file contents
source "~/.config/kak/plugins/fzf.kak/rc/modules/fzf-vcs.kak" # VCS base module
source "~/.config/kak/plugins/fzf.kak/rc/modules/VCS/fzf-git.kak" # Git support module
map global normal '<c-t>' ': fzf-mode<ret>'

# buffers
source "~/.config/kak/plugins/buffers.kak"
map global normal '<c-b>' ': pick-buffers<ret>'



# lsp stuff
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|zig|c|cpp) %{
   lsp-enable-window
}
lsp-auto-hover-enable
lsp-auto-signature-help-enable

# for log
#set-option global lsp_cmd "kak-lsp -s %val{session} -vvv --log /tmp/kak-lsp.log"


# clipboard
map global user p -docstring 'paste from clipboard' '!xsel -bo<ret>uU'
map global user y -docstring 'copy to clipboard' '<a-|>xsel -bi<ret>'
