#!/bin/sh

repo=$(ls /home/jacob/dev | dmenu)

if [ -f "/home/jacob/env/$repo.nix" ]; then
  alacritty --working-directory "/home/jacob/dev/$repo" -e nix-shell "/home/jacob/env/$repo.nix"
else
  alacritty --working-directory "/home/jacob/dev/$repo" -e bash
fi
