#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.  Opens .sent files as sent
# presentations.  Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
	*\.py)black -q "$file";;
	*\.html)prettier --write "$file";;
	*\.js)prettier --write "$file";;
	*\.vue)prettier --write "$file";;
	*\.md)prettier --write "$file";;
	*\.json)prettier --write "$file";;
	*\.rs) cargo fmt ;;
	*\.c|*\.cpp) clang-format -i "$file" ;;
	# *\.hs) haskell-formatter --force --input "$file" --output "$file" ;;
esac
