#!/bin/sh


## Terminate already running bar instances
killall -q polybar

## Wait until the processes have been shut down
while pidof polybar >/dev/null; do sleep 1; done

xrandr --query | grep " connected" | cut -d" " -f1 | tac | while read m; do
  MONITOR=$m polybar --reload top &
done
