#!/bin/sh
pk() {
     local pid=$(ps -ef | sed 1d | uniq | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[kill:process]'"     | awk '{print $2}')

     if [ "x$pid" != "x" ]; then
        echo $pid | xargs kill -${1:-9}
       pk
     fi
 }

 pk
