#!/bin/sh

ffmpeg -i $1 -ar 16000 -ac 1 -c:a pcm_s16le /tmp/whispertmp.wav
~/dev/whisper.cpp/main -m ~/dev/whisper.cpp/models/ggml-small.bin -f /tmp/whispertmp.wav -tr -p 2
if [ -n "$2" ]; then
    ~/dev/whisper.cpp/main -m ~/dev/whisper.cpp/models/ggml-small.bin -f /tmp/whispertmp.wav -l "$2" -p 2
fi
